### ISSUE TITLE
2017-06-20 文章收集

### ISSUE THREAD

**Issue by byte92** [msbu-tech/weekly#38]

**Comment by byte92** [comment]
/post

- What's New In DevTools (Chrome 59)
- http://ipage.tech/2017/06/07/What-s-new-in-devtools-chrome-59/
- 最近迎来了Chrome59的版本更新，那么在DevTools又有什么新功能了呢? css&js代码使用率、全页面截屏 etc.
- Chrome, DevTools

**Comment by crispgm** [comment]
@langjun 投稿很热情！哈哈，不过现在一般得至少两周才能凑齐文章

**Comment by crispgm** [comment]
/post
- You Are Not Google
- https://blog.bradfieldcs.com/you-are-not-google-84912cf44afb
- 又是一篇告诫大家不要因为模仿大公司导致过度设计的文章
- 技术选型

**Comment by crispgm** [comment]
/post
- How scientists use Slack
- http://www.nature.com/news/how-scientists-use-slack-1.21228
- 科学家们也用 Slack 进行协作，用的深得精髓。
- Slack, Collaboration

**Comment by crispgm** [comment]
@langjun we have to delay to 06-20, not have enough articles collected

**Comment by crispgm** [comment]
/post
- 位于中国四川，内蒙，东北的巨无霸比特币采矿工厂，月电费百万元 
- http://www.xcar.com.cn/bbs/viewthread.php?tid=29924571
- 比特币矿场图
- 比特币

**Comment by crispgm** [comment]
/post
- Instagram Makes a Smooth Move to Python 3
- https://thenewstack.io/instagram-makes-smooth-move-python-3/
- Performance speed is no longer the primary worry. Time to market speed is. — Hui Ding
- Instagram, Python, Python3

**Comment by crispgm** [comment]
/post
- The Infrastructure Behind Twitter: Scale
- https://blog.twitter.com/engineering/en_us/topics/infrastructure/2017/the-infrastructure-behind-twitter-scale.html
- Twitter scale的底层架构，比较运维向，100万行puppet配置代码
- Twitter, 基础架构
