### ISSUE TITLE
2016-10-25 内容收集

### ISSUE THREAD

**Issue by crispgm** [msbu-tech/weekly#4]

**Comment by crispgm** [comment]
http://openresty.org/slides/Optimizing-Lua-Applications-for-LuaJIT-and-OpenResty.pdf

**Comment by crispgm** [comment]
http://www.sqlstyle.guide/

**Comment by crispgm** [comment]
https://slack.engineering/taking-php-seriously-cf7a60065329#.vu7qsei74

**Comment by crispgm** [comment]
http://lincode.github.io/Modularity

**Comment by crispgm** [comment]
- 路由跳转的思考
- 摘要：作者想要解决一个实际需求：各种页面跳转造成的引用耦合。在设计解决方案时，还要提前预知一些坑和风险，为未来业务扩展考虑。作者最终选择了URLRoute+中间人的混合方案，医疗的BMRouter也是这种思路。文章写得非常认真，每个方案的优缺点都详细列出。列出参考文章更是值得阅读。 
- 标签: 引用依赖 解耦 URLRouter
- http://awhisper.github.io/2016/06/12/%E8%B7%AF%E7%94%B1%E8%B7%B3%E8%BD%AC%E7%9A%84%E6%80%9D%E8%80%83/

**Comment by haharazer** [comment]
Google 搜索结果正式 AMP 化
https://www.oschina.net/news/78151/google-amp
APM介绍：https://imququ.com/post/amp-project.html

**Comment by haharazer** [comment]
产品级微服务的八大原则
http://colobu.com/2016/10/16/microservices-in-production-notes/
uber的微服务实践总结

**Comment by crispgm** [comment]
@haharazer 赞！有没有传说中的原创

**Comment by crispgm** [comment]
Redis 为什么用跳表而不用平衡树？

http://gold.xitu.io/post/57fa935b0e3dd90057c50fbc

**Comment by crispgm** [comment]
日请求超亿级、同时在线活动800+：QQ会员活动运营系统架构实践

http://mp.weixin.qq.com/s?__biz=MjM5MDE0Mjc4MA==&mid=2650994472&idx=1&sn=a36467e996836eb010333d54e06fd22d&chksm=bdbf0f7b8ac8866d0549a2a294755bb7ca83117902e9c3d551016c8eafb5403a444f35b0dc7e&mpshare=1&scene=1&srcid=1020BxtZbXJAhmm07d5gmZR2#rd

**Comment by crispgm** [comment]
https://github.com/xitu/gold-miner/blob/8f0dbc8bb13ef50a8b6de2cb8cca30215cd3f491/TODO/bringing-Pokemon-GO-to-life-on-Google-Cloud.md
